# Generated by Django 3.1.1 on 2020-09-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuesday', '0002_auto_20200916_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=70)),
                ('edate', models.CharField(max_length=70)),
                ('eposition', models.CharField(max_length=70)),
                ('esallery', models.CharField(max_length=70)),
                ('eleft', models.CharField(max_length=70)),
            ],
        ),
    ]
